language: python

python:
  - "2.7"

cache: pip

branches:
  only: 
    - staging

before_install:
  - cd ..
  - git clone https://github.com/arendondiosa/apidocs.git private

install:
  - pip install -U pip wheel
  - pip install pylint

script:
  - python github-actions/run_pylint.py --fail-under=6.49 --rcfile='github-actions/.pylintrc' --path='github-actions' --service='test_travis_service' --version='python_2'

deploy:
  - provider: script
    # if: type = push
    on:
      branch:
        staging
    script: bash github-action/scripts/deploy.sh