name: Tests Staging

on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    outputs:
      js-files: ${{ steps.js-files.outputs.js-files }}
      migration-files: ${{ steps.js-files.outputs.migration-files }}
      python-files: ${{ steps.js-files.outputs.python-files }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: test
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"
      - id: js-files
        name: JS files
        run: echo '::set-output name=js-files::$(echo python test/filter_git_files.py --extension=".js")' | bash
      - id: python-files
        name: Python files
        run: echo '::set-output name=python-files::$(echo python test/filter_git_files.py --extension=".py")' | bash
      - id: migrations-files
        name: Migrations files
        run: echo '::set-output name=migrations-files::$(echo python test/filter_git_files.py --extension=".py" --migrations-path="migrations/")' | bash
  test-js:
    runs-on: ubuntu-latest
    name: JS test
    needs: pre-commit
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: js-files-test
      name: JS files
      run: echo ${{needs.pre-commit.outputs.js-files}}
  test-py:
    runs-on: ubuntu-latest
    name: Python test
    needs: pre-commit
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: py-files-test
      name: Python files
      run: echo ${{needs.pre-commit.outputs.py-files}}
  test-migrations:
    runs-on: ubuntu-latest
    name: Migrations test
    needs: pre-commit
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: py-files-test
      name: Python files
      run: echo ${{needs.pre-commit.outputs.migrations-files}}
