name: Tests Staging

on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  ############################################################################
  # Lint jobs
  ############################################################################
  lint-py:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-2.7-pip-${{ hashFiles('**/setup.py') }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '2.7'
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          pip install -U pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint==1.9.5
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run python lint
        run: python run_pylint.py --fail-under=8.55 --path='src'
  lint-js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Cache node
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-13-${{ hashFiles('**/src/js/package-lock.json') }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Install node dependencies
        run: |
          cd src/js/
          npm install .
      - name: Show node environment
        run: |
          node --version
          npm --version
      - name: Run JS lint
        run: |
          cd src/js/
          npm run lint
  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-3.8-pip-${{ hashFiles('**/setup.py') }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run YAML lint
        run: yamllint yaml
    