name: Tests Staging

on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    outputs:
      js-files: ${{ steps.js-files.outputs.js-files }}
      migration-files: ${{ steps.migration-files.outputs.migration-files }}
      py-files: ${{ steps.python-files.outputs.py-files }}
      hello: ${{ steps.hello.outputs.hello }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: test
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"
      - id: js-files
        name: JS files
        run: |
          FILES=$(python test/filter_git_files.py --extension=".js")
          echo ::set-output name=js-files::$FILES
      - id: py-files
        name: Python files
        run: |
          FILES=$(python test/filter_git_files.py --extension=".py")
          echo ::set-output name=py-files::$FILES
      - id: migration-files
        name: Migration files
        run: |
          FILES=$(python test/filter_git_files.py --extension=".py" --migrations-path="migrations/")
          echo "::set-output name=migration-files::$FILES"
      - id: hello
        name: Test job
        run: |
          echo "::set-output name=hello::Hello World"
  test-js:
    runs-on: ubuntu-latest
    name: JS test
    needs: pre-commit
    steps:
    - id: js-files-test
      name: JS files
      run: echo ${{needs.pre-commit.outputs.js-files}}
  test-py:
    runs-on: ubuntu-latest
    name: Python test
    needs: pre-commit
    steps:
    - id: py-files-test
      name: Python files
      run: echo ${{needs.pre-commit.outputs.py-files}}
  test-migrations:
    runs-on: ubuntu-latest
    name: Migrations test
    needs: pre-commit
    steps:
    - id: py-files-test
      name: Python files
      run: echo ${{needs.pre-commit.outputs.migration-files}}
  hello:
    runs-on: ubuntu-latest
    name: Migrations test
    needs: pre-commit
    steps:
    - id: py-files-test
      name: Python files
      run: echo ${{needs.pre-commit.outputs.hello}}
