name: Tests Staging

on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  ############################################################################
  # Lint jobs
  ############################################################################
  lint-py:
    name: Lint Python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-3.8-pip-${{ hashFiles('**/setup.py') }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run python lint
        run: pylint src
  # lint-js:
  #   name: Lint JS
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v2
  #     - name: Cache node
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-13-${{ hashFiles('**/lektor/admin/package-lock.json') }}
  #     - name: Setup node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '13'
  #     - name: Install node dependencies
  #       run: |
  #         cd lektor/admin/
  #         npm install .
  #         npm run webpack
  #     - name: Show node environment
  #       run: |
  #         node --version
  #         npm --version
  #     - name: Run JS lint
  #       run: |
  #         cd lektor/admin/
  #         npm run lint
  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-3.8-pip-${{ hashFiles('**/setup.py') }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run YAML lint
        run: yamllint yaml
    