name: CI Staging

on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  lint-py:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '2.7'
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          pip install -U pip wheel
          pip install pylint
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run python lint
        run: |
          echo "Python lint"
  test-py:
    needs: lint-py
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '2.7'
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          pip install -U pip wheel
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run python test
        run: |
          echo "Python Tests"
  lint-js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Javascript
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Show python environment
        run: |
          node --version
      - name: Run JS lint
        run: |
          echo "JS lint"
  test-js:
    needs: lint-js
    name: Test Javascript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Javascript
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Show python environment
        run: |
          node --version
      - name: Run JS test
        run: |
          echo "JS test"
