name: Test 1

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job_1:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.username }} ${{ secrets.token }}
